### ISSUE TITLE
Is this licensed/copyrighted?

### ISSUE THREAD

**Issue by ctian1** [t7seven7t/IntakeSnippets#1]

**Comment by t7seven7t** [comment]
I suppose I forgot to license this. I added the MIT license, basically you can do whatever you want with this code as long as somewhere (even in the jar) there's a notice about using or modifying code taken from this repo. I'm not really too fussed about that though and it was the most permissive license I could find and I'm too lazy to write one.

Anyway good to see another developer interested in Intake. I hope some of this code helps you out.

**Comment by ctian1** [comment]
Thanks, the code is very helpful. It's the only public repo I've found that uses Intake with Bukkit. Intake looks really awesome along with this repo.
